import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Yoodo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-bg-300">{children}</body>
    </html>
  );
}
