import type { Metadata } from "next";
import StoreProvider from "@/store/StoreProvider";
import "@/css/globals.css";
import MenuSidebar from "@/components/layouts/MenuSidebar";

export const metadata: Metadata = {
  title: "Yoodo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-bg-300">
        <StoreProvider>
          <main className={`mt-3 transition-all duration-300 ease-in-out `}>
            <MenuSidebar />
            <div>{children}</div>
          </main>
        </StoreProvider>
      </body>
    </html>
  );
}
